[package]
name = "vcf_pheno_pose"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
csv = "1.2.2"
rust-htslib = "0.44.1"
